<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

In [2]:
import numpy as np

### Exercise 1 (Total recall)

| Term    |  Brief description  |   
| :--- | :--: | 
| Subsetting  |  to select a subset of data from a list or array |  
| Indexing   |  to pick a single element from a list or array  |  
| Slicing  |  to select a range of elements from a list or array  |   
| Masking  | a way of subsetting a NumPy array that allows the true/false answer to act as a mask by only showing the true subset  |


### Exercise 2 (Show me the ‘odd’ letters)

In [71]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

x = np_array_2d    # contains different data types 
y = x[:,0]
z = y.astype(int) % 2

array = np.array(z)

mask = ~(array == 0)
mask

np_array_2d[mask,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

### Exercise 3  

#### Question

In [ ]:
change:
values below 50 to -1,
values above 50 to +1, and
values equal to 50 to 0.
You should end up with:

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]

#### Answer

In [123]:
py_list = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

x = np.array(py_list)

mask = x<50
x[mask] = -1  # masking all the 'True' values to -1

mask_2 = x>50
x[mask_2] = 1

mask_3 = x==50
x[mask_3] = 0

print(x)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
